// <auto-generated />
namespace onlineStore101.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class countryInStateModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(countryInStateModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202108261336526_countryInStateModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
